import React, { useState } from 'react';
import {
  AboutWrapper,
  ContentContainer,
  Video,
  VideoContainer,
  VideoControls,
  VideoControlsContainer,
} from './About.styles';
import { Button } from '../../styles/sharedStyledComponents';

export const About = () => {
  const [videoIndex, setVideoIndex] = useState(0);
  const videos = [
    'https://videos.pexels.com/video-files/5607745/5607745-uhd_2560_1440_30fps.mp4',
    'https://videos.pexels.com/video-files/5548361/5548361-uhd_2560_1440_25fps.mp4',
    'https://videos.pexels.com/video-files/3571264/3571264-uhd_2560_1440_30fps.mp4',
  ];

  return (
    <AboutWrapper>
      <VideoContainer>
        <Video src={videos[videoIndex]} muted autoPlay loop></Video>
        <VideoControlsContainer>
          <VideoControls onClick={() => setVideoIndex(0)} />
          <VideoControls onClick={() => setVideoIndex(1)} />
          <VideoControls onClick={() => setVideoIndex(2)} />
        </VideoControlsContainer>
      </VideoContainer>
      <ContentContainer>
        <span>Why choose us?</span>
        <h3>Nature's Majesty Awaits you</h3>
        <p>This is just a random text that will be generated by AI</p>
        <Button>Read More</Button>
      </ContentContainer>
    </AboutWrapper>
  );
};
